name: Rust Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev --no-install-recommends

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build Binaries
        run: |
          cross build --release --target x86_64-unknown-linux-gnu --features cross
          #cross build --release --target aarch64-unknown-linux-gnu --features cross
          mkdir -p bin/amd64 bin/arm64
          cp target/x86_64-unknown-linux-gnu/release/rustpbx bin/amd64/
          cp target/x86_64-unknown-linux-gnu/release/sipflow bin/amd64/
          #cp target/aarch64-unknown-linux-gnu/release/rustpbx bin/arm64/
          #cp target/aarch64-unknown-linux-gnu/release/sipflow bin/arm64/



      - name: Upload amd64 rustpbx to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/amd64/rustpbx
          asset_name: rustpbx_amd64
          tag: ${{ github.ref }}
          overwrite: true
          
      - name: Upload amd64 sipflow to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/amd64/sipflow
          asset_name: sipflow
          tag: ${{ github.ref }}
          overwrite: true
